version: "3.9"

services:
  app: &app
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        RUBY_VERSION: '3.0.1'
        BUNDLER_VERSION: '2.2.16'
        NODE_MAJOR: '14'
        YARN_VERSION: '1.22.5'
    environment:
      - TZ=Asia/Tokyo
  backend: &backend
    <<: *app
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - bundle:/bundle
      - node_modules:/app/node_modules
      - mysql:/var/lib/mysql
    depends_on:
      - mysql
  rails:
    <<: *backend
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - '3000:3000'
  runner:
    <<: *backend
    command: /bin/bash
    ports:
      - '3002:3002'
  mysql:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'

volumes:
  bundle:
  node_modules:
  mysql:
