name: Deploy service with AWS Copilot

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Setup AWS Copilot
      run: |
        curl -Lo copilot-linux https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux
        chmod +x copilot-linux
        sudo mv copilot-linux /usr/local/bin/copilot

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.1
        bundler-cache: true

    - name: Assets precompile
      run: |
        bin/rails assets:precompile

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
  
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
  
    - name: Build docker image
      id: docker-build
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: .
        file: ./Dockerfile.prod
        build-args: |
          RUBY_VERSION=3.0.1
          BUNDLER_VERSION=2.2.16
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/chronos/rails:${{ github.sha }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    # - name: Deploy Rails service to dev environment
    #   run: |
    #     copilot svc deploy --app chronos --env dev --name rails
    # TODO: Run migratoin before copilot sevice deployment
    # - name: Excecute database migration
    #   run: |
    #     # https://aws.github.io/copilot-cli/docs/commands/svc-exec/
    #     copilot svc exec \
    #       --command 'bin/rails db:migrate' \
    #       --app chronos \
    #       --name rails \
    #       --env dev
